# Generated by Django 4.2.30 on 2026-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_question_per_attempt'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(fields=('user', 'quiz'), name='unique_attempt_per_user_per_quiz'),
        ),
    ]
